//! Ten authored rooms. Solution routes are ordinary clicks, not state injection.
use super::{Axis, Room};
pub const ROOMS: &[Room] = &[
    Room {
        name: "Equal and opposite",
        hint: [
            "One empty cell left, four right.",
            "A flip trades the two empty gaps.",
        ],
        rows: &["######", "......", "######"],
        start: &[7],
        goals: &[10],
        solution: &[(0, Axis::Horizontal)],
    },
    Room {
        name: "Around the pillar",
        hint: ["Walls end a corridor.", "Try both axes to turn the corner."],
        rows: &[".....", "..#..", "..#..", ".....", "....."],
        start: &[5],
        goals: &[8],
        solution: &[
            (0, Axis::Horizontal),
            (0, Axis::Vertical),
            (0, Axis::Horizontal),
            (0, Axis::Vertical),
        ],
    },
    Room {
        name: "Borrow a boundary",
        hint: [
            "A neighbor is a movable wall.",
            "Shift one to change the other's gap.",
        ],
        rows: &["......", "......", "######"],
        start: &[0, 2],
        goals: &[10, 0],
        solution: &[
            (0, Axis::Horizontal),
            (1, Axis::Horizontal),
            (0, Axis::Vertical),
            (0, Axis::Horizontal),
            (1, Axis::Horizontal),
        ],
    },
    Room {
        name: "Leave to return",
        hint: [
            "A goal is a place, never a lock.",
            "A may need to leave and come back.",
        ],
        rows: &[".....", "..#..", ".....", "..#..", "....."],
        start: &[0, 4, 20],
        goals: &[0, 22, 19],
        solution: &[
            (1, Axis::Horizontal),
            (2, Axis::Horizontal),
            (1, Axis::Vertical),
            (0, Axis::Horizontal),
            (1, Axis::Horizontal),
            (2, Axis::Vertical),
            (0, Axis::Horizontal),
            (2, Axis::Vertical),
        ],
    },
    Room {
        name: "Narrow windows",
        hint: [
            "Small gaps make useful landings.",
            "Look at the ghost before you commit.",
        ],
        rows: &["......", ".#..#.", "......", "..##..", "......"],
        start: &[0, 5, 24],
        goals: &[29, 28, 26],
        solution: &[
            (1, Axis::Vertical),
            (0, Axis::Horizontal),
            (1, Axis::Horizontal),
            (0, Axis::Vertical),
            (2, Axis::Vertical),
            (1, Axis::Horizontal),
            (2, Axis::Vertical),
            (2, Axis::Horizontal),
            (1, Axis::Horizontal),
        ],
    },
    Room {
        name: "Split channels",
        hint: [
            "The channels meet at their ends.",
            "Use a neighbor to stop one cell short.",
        ],
        rows: &["......", "..#...", "......", "...#..", "......", "##..##"],
        start: &[0, 5, 32],
        goals: &[33, 32, 28],
        solution: &[
            (0, Axis::Vertical),
            (1, Axis::Horizontal),
            (1, Axis::Vertical),
            (1, Axis::Horizontal),
            (2, Axis::Vertical),
            (1, Axis::Vertical),
            (2, Axis::Horizontal),
            (0, Axis::Horizontal),
            (0, Axis::Vertical),
            (1, Axis::Vertical),
        ],
    },
    Room {
        name: "Chain reaction",
        hint: [
            "One useful gap leads to another.",
            "You can always undo an experiment.",
        ],
        rows: &["......", ".#..#.", "......", ".#..#.", "......", "......"],
        start: &[0, 5, 30],
        goals: &[35, 34, 8],
        solution: &[
            (0, Axis::Vertical),
            (1, Axis::Vertical),
            (2, Axis::Horizontal),
            (2, Axis::Vertical),
            (1, Axis::Horizontal),
            (2, Axis::Horizontal),
            (0, Axis::Horizontal),
            (0, Axis::Vertical),
            (0, Axis::Horizontal),
            (1, Axis::Horizontal),
            (2, Axis::Vertical),
        ],
    },
    Room {
        name: "Four corners",
        hint: [
            "Four tokens, one conversation.",
            "Let a helper trade places with space.",
        ],
        rows: &["......", "..##..", "......", "......", "..##..", "......"],
        start: &[0, 5, 30, 35],
        goals: &[0, 33, 29, 3],
        solution: &[
            (3, Axis::Horizontal),
            (3, Axis::Vertical),
            (2, Axis::Horizontal),
            (0, Axis::Vertical),
            (2, Axis::Vertical),
            (3, Axis::Horizontal),
            (1, Axis::Horizontal),
            (1, Axis::Vertical),
            (1, Axis::Horizontal),
            (0, Axis::Vertical),
            (1, Axis::Horizontal),
            (2, Axis::Vertical),
        ],
    },
    Room {
        name: "Crossroads",
        hint: ["A is already home.", "That does not mean its work is done."],
        rows: &["......", ".#..#.", "..##..", "......", ".#..#.", "......"],
        start: &[0, 5, 30, 35],
        goals: &[0, 34, 29, 4],
        solution: &[
            (1, Axis::Horizontal),
            (3, Axis::Vertical),
            (1, Axis::Horizontal),
            (0, Axis::Horizontal),
            (0, Axis::Vertical),
            (1, Axis::Horizontal),
            (0, Axis::Vertical),
            (2, Axis::Horizontal),
            (1, Axis::Vertical),
            (1, Axis::Horizontal),
            (2, Axis::Vertical),
            (3, Axis::Horizontal),
            (0, Axis::Horizontal),
            (2, Axis::Vertical),
        ],
    },
    Room {
        name: "The gap orchestra",
        hint: [
            "Every token helps shape the room.",
            "Finish with all four symbols matched.",
        ],
        rows: &["......", "..##..", ".#..#.", "......", "..##..", "......"],
        start: &[0, 5, 30, 35],
        goals: &[0, 33, 21, 3],
        solution: &[
            (0, Axis::Horizontal),
            (1, Axis::Vertical),
            (1, Axis::Horizontal),
            (2, Axis::Vertical),
            (0, Axis::Horizontal),
            (2, Axis::Vertical),
            (2, Axis::Horizontal),
            (1, Axis::Vertical),
            (1, Axis::Horizontal),
            (2, Axis::Vertical),
            (2, Axis::Horizontal),
            (1, Axis::Vertical),
            (1, Axis::Horizontal),
            (3, Axis::Vertical),
            (3, Axis::Horizontal),
            (0, Axis::Horizontal),
        ],
    },
];
